server:
  port: 8771
spring:
  application:
    name: product-service
  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

profile: dev
